name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclencher le workflow sur des pushs vers la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd gengine # Naviguer vers le dossier gengine
          npm install

      - name: Build
        run: |
          cd gengine # Naviguer vers le dossier gengine
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gengine/build
